apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-
spec:
  serviceAccountName: gitclone-sa
  pipelineRef:
    name: build-and-deploy
  params:
  - name: git-url
    value: "git@github.com:saurav116/pipelines-vote-api.git"
  - name: IMAGE
    value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/pipelines-vote-api"
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
